Add Vulkan Backend
LPGhatguy/yakui pull request #86
Opened 2023-01-27 07:47 UTC by kanerogers

## Background
Closes #85

2023-02-02 00:14 UTC, kanerogers commented
Alright @LPGhatguy - I think this is ready to go!

2023-02-03 06:53 UTC, Ralith requested changes

2023-02-03 06:53 UTC, Ralith commented on crates/yakui-vulkan/shaders/main.frag
> +#extension GL_ARB_shading_language_420pack : enable
I don't think either of these do anything here.

2023-02-03 08:59 UTC, kanerogers commented
Rats, thought I’d killed those. Thanks!

On Fri, 3 Feb 2023 at 5:54 pm, Benjamin Saunders ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In crates/yakui-vulkan/shaders/main.frag
> <https://github.com/LPGhatguy/yakui/pull/86#discussion_r1095412233>:
>
> > +#extension GL_ARB_separate_shader_objects : enable
> +#extension GL_ARB_shading_language_420pack : enable
>
> I don't think either of these do anything here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LPGhatguy/yakui/pull/86#pullrequestreview-1282365239>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPNXZ2QXM5VRTLEI4BPFGDWVSTQZANCNFSM6AAAAAAUIMQD4M>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-06 23:54 UTC, LPGhatguy requested changes
I got tied up with some stuff over this last week and didn't finish my review. Here's what I've got for you so far, though!

2023-02-07 00:18 UTC, Ralith commented on crates/yakui-vulkan/src/vulkan_context.rs
> +    pub device: &'a ash::Device,
`Device` has most of the function pointer tables, so it's pretty big.

2023-02-07 01:12 UTC, kanerogers commented on .vscode/tasks.json
> +}
Yes! Good point. Removed.

2023-02-07 01:13 UTC, kanerogers commented on crates/yakui-vulkan/src/vulkan_context.rs
> +    /// A valid Vulkan device that has the `VkPhysicalDeviceDescriptorIndexingFeatures.descriptorBindingPartiallyBound` feature enabled
Yep, absolutely.

2023-02-07 01:14 UTC, kanerogers commented on crates/yakui-vulkan/src/vulkan_texture.rs
> +pub struct VulkanTextureCreateInfo<T: AsRef<[u8]>> {
> Bounds on structs express the wrong thing for most people. They are infectious, redundant, sometimes nearsighted, and often confusing.

Yikes. :P Okay, point taken!

2023-02-07 01:16 UTC, kanerogers commented on crates/yakui-vulkan/src/vulkan_context.rs
> +        device.free_command_buffers(self.command_pool, std::slice::from_ref(&command_buffer));
Yeah, it's pretty neat - something I stole from @Ralith! In my own code I generally alias it to something like `slice_from_ref` but I just wanted to be a bit clearer here.

2023-02-07 01:17 UTC, kanerogers commented on crates/yakui-vulkan/src/vulkan_context.rs
> +        device.free_command_buffers(self.command_pool, std::slice::from_ref(&command_buffer));
Yeah, it's pretty neat - something I stole from @Ralith! In my own code I generally alias it to something like `slice_from_ref` but I just wanted to be a bit clearer here.

2023-02-07 01:21 UTC, kanerogers commented on crates/yakui-vulkan/src/vulkan_texture.rs
> +        yakui::paint::TextureFormat::Rgba8Srgb => vk::Format::R8G8B8A8_UNORM,
As dicussed earlier, yes, it aboslutely should be! But I did have some strangeness with how images were being decoded with the `image` crate. I'll dig a little deeper into this today.

2023-02-18 00:38 UTC, LPGhatguy approved these changes
After keeping you hanging for forever (sorry!) I'm going to go ahead and merge this as-is. I'll poke at it afterwards and we can always land follow-up changes.

2023-02-18 00:39 UTC, merged